services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: project-backend
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    networks:
      - project-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5001/api/v1"
    image: project-frontend:latest
    container_name: project-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - project-net

networks:
  project-net:
    driver: bridge