services:
  db:
    image: postgres:16-alpine
    container_name: project-db
    environment:
      POSTGRES_DB: your_db_name       
      POSTGRES_USER: your_user      
      POSTGRES_PASSWORD: your_password  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: project-backend
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    env_file:
      - /backend/src/WebApi/.env
    depends_on:
      - db
    networks:
      - internal-net
      - frontend-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5001/api/v1"
    image: project-frontend:latest
    container_name: project-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend-net

networks:
  internal-net:
    driver: bridge
    internal: true
  frontend-net:
    driver: bridge
    
volumes:
  postgres_data: